[project]
name = "blender-pose-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "naroah", email = "givefacegod@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
blender-pose-tools = "blender_pose_tools:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
